name: Unit tests

on:
  pull_request:
  push:
    branches: [master]

jobs:
  unit-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y cmake gcc make zlib1g-dev

      - name: Test with coverage
        timeout-minutes: 15
        run: make test

      - name: Verify coverage badge
        run: git diff --exit-code badges/coverage.json
